service: car-value

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'ap-south-1'}
  bundle:
    linting: false
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  timeout: 10
  logRetentionInDays: 5
  lambdaHashingVersion: 20201221 # https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
  region: ap-south-1
  profile: leaks
  logs:
    httpApi: true
  httpApi:
    # metrics: true # Enable if you need
    cors: true
  environment:
    DB_URI: ${env.DB_URI}
    COOKIE_KEY: ${env.COOKIE_KEY}

functions:
  api:
    handler: dist/serverless.handler
    # reservedConcurrency: 100
    events:
      - http: ANY /{proxy+}

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
